# My Service also exposes port 80, but does not need to match
# the spec.selector matches the labels of  deployment above
apiVersion: v1
kind: Service
metadata:
  name: dbdc
  namespace: dc-db-demo-app
  labels:
    app: dbdc
    service: dbdc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: dbdc

---
# Our virtual service exposes our internal K8s service to our istio gateway
# The Istio gateway handles SSL and is already internet exposed.
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: dbdc-app
  namespace: dc-db-demo-app
spec:
  hosts:
    # claim your domain here! (must be sub of demo.region.circleci-labs.com)
    - dbdcbin.demo.namer.circleci-labs.com
  gateways:
    # gateway name is region specific
    - istio-ingress/namer-istio-gateway-demos
  http:
    - route:
        - destination:
            host: dbdcbin.dbdc.svc.cluster.local
            port:
              number: 80
status: {}